version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password_here
      MYSQL_DATABASE: schedulai
      MYSQL_USER: scheduler
      MYSQL_PASSWORD: scheduler_pass
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  scheduling_engine:
    build:
      context: .
      dockerfile: services/scheduling_engine/Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: scheduler
      DB_PASSWORD: scheduler_pass
      DB_NAME: schedulai
    ports:
      - "5001:5001"

  conflict_detector:
    build: ./services/conflict_detector
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: scheduler
      DB_PASSWORD: scheduler_pass
      DB_NAME: schedulai
    ports:
      - "5002:5002"

  analytics:
    build: ./services/analytics
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: scheduler
      DB_PASSWORD: scheduler_pass
      DB_NAME: schedulai
    ports:
      - "5003:5003"

  web:
    build: ./services/web
    depends_on:
      - scheduling_engine
      - conflict_detector
      - analytics
      - db
      - redis
    environment:
      DB_HOST: db
      DB_USER: scheduler
      DB_PASSWORD: scheduler_pass
      DB_NAME: schedulai
      REDIS_URL: redis://redis:6379
      SCHEDULING_ENGINE_URL: http://scheduling_engine:5001
      CONFLICT_DETECTOR_URL: http://conflict_detector:5002
      ANALYTICS_URL: http://analytics:5003
      SECRET_KEY: change-me
    ports:
      - "5000:5000"

  nginx:
    build: ./services/nginx
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./services/nginx/ssl:/etc/nginx/ssl

volumes:
  db_data: