name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python 3.11
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. (Optional) Cache pip downloads between runs
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      # 5. Run pytest with coverage
      - name: Run tests & generate coverage
        run: |
          pytest --cov=./libs/scheduling \
                 --cov-branch \
                 --cov-report=term-missing \
                 --cov-report=html

      # 6. Upload the HTML coverage report for later inspection
      - name: Upload coverage report
        uses: actions/upload-artifact@v1
        with:
          name: coverage-report
          path: htmlcov/
